services:
  api:
    # image: ghcr.io/pzyyll/ollama-api-proxy:main-latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    env_file:
      - .env
    restart: unless-stopped
